### ISSUE TITLE
在转发爬取时遇到问题

### ISSUE THREAD

**Issue by Jaybore** [XWang20/WeiboCrawler#12]
作者您好！在我运行抓发爬取命令时遇到了如下问题：
`2022-03-03 14:53:17 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://m.weibo.cn/api/statuses/repostTimeline?id=4742865873797609&page=1> (referer: None)
2022-03-03 14:53:17 [scrapy.core.scraper] ERROR: Spider error processing <GET https://m.weibo.cn/api/statuses/repostTimeline?id=4742865873797609&page=1> (referer: None)
Traceback (most recent call last):
  File "C:\Users\17243\Desktop\WeiboCrawler\venv\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "C:\Users\17243\Desktop\WeiboCrawler\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "C:\Users\17243\Desktop\WeiboCrawler\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "C:\Users\17243\Desktop\WeiboCrawler\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\17243\Desktop\WeiboCrawler\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\17243\Desktop\WeiboCrawler\WeiboCrawler\spiders\repost.py", line 23, in parse
    all_page = js['data']['max']
KeyError: 'data'
`
初步分析是由于需要登录造成的，请教下您如何解决？

**Comment by XWang20** [comment]
可以在config里添加cookie解决。微博对转发做了限制，没有cookie爬不了了

**Comment by Jaybore** [comment]
谢谢大佬！ 问题已经解决了~


还有一个问题就是目前输出的CSV文件中文显示乱码，但是我目前没有找到编码方式的命令行，
如果可以的话还请指个路




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XWang20/WeiboCrawler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 中午11:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XWang20/WeiboCrawler] 在转发爬取时遇到问题 (Issue #12)





 
可以在config里添加cookie解决。微博对转发和评论做了限制，现在没有cookie爬不了了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XWang20** [comment]
可以参考这个issue
https://github.com/XWang20/WeiboCrawler/issues/7#issuecomment-984324671

**Comment by Jaybore** [comment]
再次感谢大佬！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XWang20/WeiboCrawler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XWang20/WeiboCrawler] 在转发爬取时遇到问题 (Issue #12)





 
可以参考这个issue
 #7 (comment)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MengskIV** [comment]
我也遇到了相同的情况，但在settings.py文件中添加了cookie仍然没有解决问题。
请问这可能是由于什么

**Comment by MengskIV** [comment]
我也遇到了相同的情况，但在settings.py文件中添加了cookie仍然没有解决问题。
请问这可能是由于什么

**Comment by XWang20** [comment]
> 我也遇到了相同的情况，但在settings.py文件中添加了cookie仍然没有解决问题。
> 请问这可能是由于什么

确定用的是m.weibo.cn站点的cookie嘛
